language: nix
nix: 2.3.3
# see https://docs.travis-ci.com/user/languages/nix
# and https://nixos.wiki/wiki/Nix_on_Travis
sudo: false
before_install:
- sudo mkdir -p /etc/nix
# make sure no browser is left over that can disturb the karma tests (nix-shell provides the browsers!)
- sudo apt-get remove google-chrome-stable -y
- sudo apt-get remove chromium-browser -y
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null

env:
  global:
    - # GitHub Environment variables for NPM version patch
    - secure: "nMPPHfJ5qiIBbJ+oOQP0OaWC11muxmNb2HQ119QN7gHyKDaTPmk7pK3exV9KV+E6kx5HuZAKXHbxO1gfeKjfOrqzuEFR13hn6Lr3/HrsO9QGlK4a+F95q3zWvrv1KqhFPoSRbdpJcFHYb26wx59VR8raz9uTu10SKREuDjLDcfhs0NFMWzNIRvD0YO8eHTbBx1f85bo9KC0/3PuS69/NTiy5HcDU0zJpz6l7sN5iSorRdin8gR9KY6ZWyV53KwgBoB9bVfq8VbK23s3d/Xu26J88AZ0alk0vanOpw/aXyaFjbk/+Z1vA0mROXievfr6kyWGwXKRLM/9jjYTNgXSTtOq+lEFZq5Xp/ArRsUJttgAgzmpoqhhaTnnzmZ1lP06IG6giZZTeoKt/6NzgS6nL4PINb78fcOAsZ/a76CpP9LWuSgTAtB7gOSz6HRJgMV83nsrwduiBmJmGbD63d0gU93dGEbUydJzczwsGsDB0JPZTDZ4bL8TH5ASDdnhnb4yYp9T90pfFvWeFf2JFDrlRy62wV2xsL4P5FfOPTyzIzu9XuEIpI3TWATNGjhhbvdSqTtur69i92Ksri3V36I3JKNHqEMzs00qMTVn+g/A1zxGFP4TTUXDB4pBz5EwmDSTHixK68VfupuXIEh61HoEDEMg+amtjuUsjSvXDBoD9wd8="
    - secure: "hmFV1vAJPmgYR+NvSecGc3WmMCCE2BNUKvQsItPKdyav0IbrNtnFBqmz3IzAaFnX8sNog8Z421/+SvjCAEf9ZZA4djbr3EZl4NEnzHKrMQeKme1HCOoWSMG4sjMbPvsHvNBlhe5bamGDHgbXDCoGqTCvYtOB8p/iksj70NL6kpvB0Y95Gg1WwyYvjxqK1Hh+V8oCRbZ7BthMXXfDwG0ge5UMOl6ayeZSvHcu+sHhVQycp2TNFFk8Ahq9xdjJs64nMwi/OI0/mXVrwwkD46BqyZ7ljNyOnxkUwzYLA/cftBXHp8pMAj/4PqE15VGihvt4cdscpjDZn+qbRmPzmTzJNIYBKd7jG8GhbPbdFLsU5XKdfwN1dc3/mjmEY/Y6lE6SuI7PQQJwFSmWaRf+KWOdqzpP2GnheikpIi5f9s45IpKNvSWeOWKAmklvW8SlTy+lbui52jzbK1cwesrUqbtubr30ozSC2pQUTyauwAF5L256aW56xExfR1s/lxjApnuwFv1jtQIJDiIP48z9kMbRvR8MjbeJexP2jCv50INtf45qmNwWGYbCIjz10iMEkbGpeM+pCr9UNKJgNplwjotrpnzFSwzLPWdZZUrKWRGZcrpV+5st5b2G5cWVmYkOQCRYeJt7MwVlc6XjotForuTxMlXYtNnAmUE44WUGCW+hYIA="
    - NIXPKGS_ALLOW_UNFREE: 1

  matrix:
    - FIREFOX_VERSION="latest"
    - FIREFOX_VERSION="60-esr"

install:
- nix-shell shell-${FIREFOX_VERSION}.nix --command "yarn install"
script:
- nix-shell shell-${FIREFOX_VERSION}.nix --command "firefox --version"
- nix-shell shell-${FIREFOX_VERSION}.nix --command "google-chrome --version"
- nix-shell shell-${FIREFOX_VERSION}.nix --command "yarn run lint"
- nix-shell shell-${FIREFOX_VERSION}.nix --command "xvfb-run --server-args=\"-ac -screen 0 1920x1080x16\" yarn run test:once"
- nix-shell shell-${FIREFOX_VERSION}.nix --command "xvfb-run --server-args=\"-ac -screen 0 1920x1080x16\" yarn run e2e"

after_success:
- nix-shell shell-${FIREFOX_VERSION}.nix --command "yarn run packagr"
# Autoincrement of patch level version:
# Tag the repo with a new patch level version tag, if this build is done on
#     'FIREFOX_VERSION = latest' and (only one of the matrix-builds is relevant)
#     this is not a pull request and (pull requests themselves should not autoincrement)
#     this branch is the master branch and (only builds on master are relevant)
#     there is no tag given (if a tag is alread given, this one will be published and should not again be tagged!)
- 'if [ "$FIREFOX_VERSION" = "latest" -a "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_TAG" = "" ]; then wget https://github.com/test-editor/commons-build-automation/raw/master/travis/deploy/tag_with_new_patch_version.sh; nix-shell shell-${FIREFOX_VERSION}.nix --command  "bash tag_with_new_patch_version.sh"; fi'
before_deploy:
- touch .npmignore
- cd dist/
deploy:
  skip_cleanup: true
  provider: npm
  email: testeditor.eng@gmail.com
  api_key:
    secure: "A39XD4GjX1cwKBi9SI70jMeDEZMx+CC+4X9VoQfnyC4IeUDEIQ123YBBkqEVJefCOQ8HLQrcm/L4ws1oJUKk8hkxAqw8iwpcIhZnfK/u6lcptKRmSzTlEsPXq3sE+B6ECUQ2JoJKMWs3X0RZPo9bh/tQZKjQRtfw5a8ZR4HjGmMUDqfl10axUILfcbg1QCzyOeBZf5aQdxuZP4VnOgeNT3diVE9RbFyLniIXh3adTdTUn5oMMR+GeWEacd6185z/wHf6wH8ejy7zIfXUzLOX1bZSIGFGQBn75kTbbt6EuH2XyZfYdxiuEdsMA6mJPDW71LHBzjvaLzZwFY7POV2xcbYZuLb05JR8Prwh63PAi34H0THxk0841ZXGFaaGqhs/K4xaf2IssX4J8x/y2TgP5mjwCjCv5NKfar0O1GI3PuMibf5W1xSf8LNpzfQiVTXzqVxQe+sLvTr9R8VCqS68xlngTPu4ydL7BDU14lDOQoEnzUL6cKp1cbiSwPuogbd9nbVHWHp1+k3aiGVwptefD3hbrDYWSncoaHMq6gFZXloxSd9g2CJIAGHKj/Wu+ti6FvdptZ89v2k7NUNkUKp3XreE45Ti5oWzgmaHTF8lUgXv1A9zHumuo2StbPrHM2gIOOoHdIFb3WnYMPD8E0NE8eCGDywPibwRXRy5cihmqTo="
  on:
    condition: "$FIREFOX_VERSION = latest"
    tags: true
    repo: test-editor/web-testexec-details
